# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 09:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('college_id', models.AutoField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=128, unique=True)),
                ('college_address', models.CharField(default='', max_length=128)),
                ('inception_year', models.DateTimeField(blank=True, default=datetime.datetime(2016, 11, 22, 15, 21, 50, 240120))),
                ('co_website', models.CharField(default='', max_length=128, unique=True)),
                ('c_ownership_type', models.CharField(default='', max_length=128)),
                ('c_area', models.IntegerField(default=0)),
            ],
        ),
    ]
