# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 09:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colleges',
            name='inception_year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 11, 22, 15, 22, 40, 980989)),
        ),
    ]
