# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 10:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20161122_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream_Master',
            fields=[
                ('college_id', models.AutoField(primary_key=True, serialize=False)),
                ('stream_id', models.IntegerField(primary_key=True)),
                ('stream_name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='colleges',
            name='inception_year',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 11, 22, 16, 10, 16, 453339)),
        ),
    ]
